openapi: 3.1.0
info:
  title: CoinGecko - Precio y Velas OHLC
  description: Consulta el precio actual y datos OHLC de cualquier criptomoneda desde CoinGecko.
  version: '1.0'
servers:
  - url: https://api.coingecko.com/api/v3
paths:
  /simple/price:
    get:
      operationId: get_crypto_price
      summary: Obtener el precio actual de una criptomoneda
      parameters:
        - name: ids
          in: query
          description: ID de la criptomoneda según CoinGecko (ej. bitcoin, ethereum, qubic, solana, etc.)
          required: true
          schema:
            type: string
        - name: vs_currencies
          in: query
          description: Moneda de referencia (ej. usd, eur, mxn, btc, eth, etc.)
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Precio actual de la criptomoneda
          content:
            application/json:
              example:
                bitcoin:
                  usd: 29345.67
                  eur: 26999.12

  /coins/{id}/ohlc:
    get:
      operationId: get_ohlc_data
      summary: Obtener datos OHLC (Open, High, Low, Close)
      parameters:
        - name: id
          in: path
          description: ID de la criptomoneda (ej. bitcoin, ethereum, solana, qubic, etc.)
          required: true
          schema:
            type: string
        - name: vs_currency
          in: query
          description: Moneda de referencia (ej. usd, eur)
          required: true
          schema:
            type: string
        - name: days
          in: query
          description: Rango de días (1, 7, 14, 30, 90, 180, 365, max)
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de velas con [timestamp, open, high, low, close]
          content:
            application/json:
              example:
                - [1622505600000, 37000.0, 37500.0, 36500.0, 37200.0]
                - [1622592000000, 37200.0, 38000.0, 37000.0, 37800.0]