openapi: 3.1.0
info:
  title: CoinMarketCap - Datos de Criptomonedas
  description: Consulta precios, volumen y capitalización de mercado de cualquier criptomoneda usando la API de CoinMarketCap.
  version: '1.0'
servers:
  - url: https://pro-api.coinmarketcap.com/v1
paths:
  /cryptocurrency/quotes/latest:
    get:
      operationId: get_crypto_data
      summary: Obtener datos actuales de una criptomoneda
      parameters:
        - name: symbol
          in: query
          description: Símbolo de la criptomoneda (ej. BTC, ETH, QUBIC)
          required: true
          schema:
            type: string
        - name: convert
          in: query
          description: Moneda de conversión (ej. USD, EUR)
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Datos de la criptomoneda
          content:
            application/json:
              example:
                status:
                  timestamp: "2025-07-28T10:00:00.000Z"
                  error_code: 0
                  error_message: null
                data:
                  BTC:
                    quote:
                      USD:
                        price: 29345.67
                        volume_24h: 15893000000
                        market_cap: 573900000000
                        percent_change_24h: 2.34
      security:
        - api_key: []
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: X-CMC_PRO_API_KEY
